cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

ecomapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('contact/', views.contact, name='contact')
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('ecomapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('orders/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

ecomapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

        def __str__(self):
            return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [ models.Index(fields=['id', 'slug']), models.Index(fields=['name']), models.Index(fields=['-created'])]

    def __str__(self):
        return self.name

ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from cartapp.forms import CartAddForm

def home(request):
    product = Product.objects.all()
    cart_add_form = CartAddForm()

    context = {'product': product, 'cart_add_form': cart_add_form}
    return render(request, 'home.html', context)

def about(request):
    return render(request, 'about.html')

def detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    cart_add_form = CartAddForm()
    context = {'product': product, 'cart_add_form': cart_add_form}
    return render(request, 'detail.html', context)

def contact(request):
    return render(request, 'contact.html')

ecomapp/templates/about.html
{% extends 'base.html' %} {% block content %}
<script
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAs19P63P8avYTvgtBzckpeI1CGkc5earE&callback=myMap"
	async
	defer></script>
<div class="about-box">
	<h3>About Us</h3>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Scelerisque fermentum
		dui faucibus in. Orci a scelerisque purus semper eget duis at tellus. Odio
		tempor orci dapibus ultrices in iaculis nunc sed. Quam viverra orci sagittis
		eu. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Quis
		hendrerit dolor magna eget est lorem ipsum dolor. Pretium nibh ipsum
		consequat nisl vel pretium lectus quam id. Interdum velit euismod in
		pellentesque. Dolor sed viverra ipsum nunc aliquet
	</p>
</div>
<div class="location-box">
	<h3>Our Location</h3>
	<iframe
		src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d261508.00616576546!2d-119.58628297856886!3d50.87763257662211!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x537e51be38a683b7%3A0xa94cb27774a83419!2sShuswap%2C%20BC%20V0E%201M1!5e0!3m2!1sen!2sca!4v1691424027932!5m2!1sen!2sca"
		width="800"
		height="550"
		style="border: 10px solid rgba(0, 136, 169, 1); border-radius: 10px; margin-top: 50px; margin-bottom: 50px;"
		allowfullscreen=""
		loading="lazy"
		referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

{% endblock %}

ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

<div class="account-info-body">
    
</div>

{% endblock %}

ecomapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>Shoe</title>
		<link rel="stylesheet" href="{% static 'css/base.css' %}" />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
			rel="stylesheet" />
	</head>
	<body>
		<div class="main-text">
			<div class="nav-bar">
				<header>
					<div class="header-title">
						<img
							src="{% static 'img/shoe-logo-removebg.png' %}"
							alt="logo"
							id="logo" />
						<h1>SHUSWAP SHOE SHOP</h1>
					</div>
					<div class="header-links">
						<nav>
							<ul class="nav-links">
								<li><a href="{% url 'home' %}">Home</a></li>
								<li><a href="{% url 'about' %}">About</a></li>
								{% with total_items=cart|length %} {% if total_items > 0 %}
								<li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
								{% endif %} {% endwith %}
							</ul>
						</nav>
						<a class="cta" href="{% url 'contact' %}"
							><button>Contact</button></a
						>
					</div>
				</header>
			</div>
			<div class="cart-items">
				{% with total_items=cart|length %} {% if total_items > 0 %}
				<p>Your cart:</p>
				<a href="{% url 'cart:cart_detail' %}">
					{{ total_items }} item{{ total_items|pluralize }} : ${{cart.total_price }}
				</a>
				{% else %} Your cart is empty. {% endif %} {% endwith %}
			</div>

			{% block content %} {% endblock %}
		</div>
		<div class="footer-container">
			<footer class="footer">
				<div class="social-icons">
					<a href="#" class="icon"
						><img src="{% static 'img/icon-facebook.png' %}" alt="Facebook"
					/></a>
					<a href="#" class="icon"
						><img src="{% static 'img/icon-twitterx.png' %}" alt="Twitter"
					/></a>
					<a href="#" class="icon"
						><img src="{% static 'img/icon-instagram.png' %}" alt="Instagram"
					/></a>
				</div>
				<div>
					<p>Copyright © 2023 Designed by Munks</p>
				</div>
			</footer>
		</div>
	</body>
</html>

ecomapp/templates/contact.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h3 style="text-align: center">Contact Us</h3>
<div class="contact-body">
	<div class="contact-box">
		<h3>By Phone</h3>
		<div>
			<img
				src="{% static 'img/phone-icon.png' %}"
				style="height: 130px; margin-top: 20px" />
		</div>
        <br>
        <h5>INTERNATIONAL</h5>
        <h4>1-999-123-4567</h4>
	</div>
	<div class="contact-box">
		<h3>By email</h3>
		<div>
			<img
				src="{% static 'img/email-icon.png' %}"
				style="height: 100px; margin-top: 40px" />
		</div>
        <br>
        <h5>EMAIL ADDRESS</h5>
        <h4>shuswapshoeshop@footwear.com</h4>
	</div>
</div>
{% endblock %}

ecomapp/templates/detail.html
{% extends 'base.html' %} {% block content %}

<div class="product-body">
	<div class="product-box">
		<div class="product-image">
			<img src="{{ product.image.url }}" alt="{{ product.name }}" />
		</div>
		<div class="product-text">
			<div class="product-info">
				<h4>{{ product.name }}</h4>
				<h5>{{ product.description }}</h5>
				{% if product.available == True %}
				<p style="color: green">In Stock</p>
				{% else %}
				<p style="color: red">None in Stock</p>
				{% endif %}
				<p>${{ product.price }}</p>
				<form action="{% url 'cart:cart_add' product.id %}" method="post">
					{{ cart_add_form }} {% csrf_token %}
					<input class="form-btn" type="submit" value="Add to cart" />
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

ecomapp/templates/home.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="home-cover">
	<div class="home-cover-text">
		<h3>
			New Collection
		</h3>
		<hr class="hr" />
		<h2>STYLISH FOOTWEAR</h2>
		<p>These shoes are definitely real and not generated via AI technology</p>
		<a class="cta" href="#product-body"><button>Shop now</button></a>
	</div>
	<div class="home-image-main"><img src="{% static 'img/orange-shoe.png' %}" /></div>
</div>
<div class="product-body" id="product-body">
	{% for p in product %}
	<div class="product-box">
		<div class="product-image">
			<img src="{{ p.image.url }}" alt="{{ p.name }}" style="height: 400px;" />
		</div>
		<div class="product-text">
			<div class="product-info">
				<h4>{{ p.name }}</h4>
				<h5>{{ p.description }}</h5>
				<p>${{ p.price }}</p>
                <a class="cta" href="{% url 'detail' p.slug %}"><button>View Item</button></a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}