cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('ecomapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('orders/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

cartapp/models.py
from django.db import models

# Create your models here.

cartapp/forms.py
from django import forms

PRODUCT_QUANTITY = [(i, str(i)) for i in range(1, 11)]

class CartAddForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ecomapp.models import Product
from .cart import Cart
from .forms import CartAddForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

cartapp/templates/cart/cart_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
<div class="cart-box">
	<h1>Your shopping cart</h1>
	{% if cart %}
	<table class="cart-table">
		<thead>
			<tr>
				<th></th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Remove</th>
				<th>Unit price</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %} {% with product=item.product %}
			<tr>
				<td>
					<img src="{{ product.image.url }}" />
				</td>
				<td>{{ product.name }}</td>
				<td>
					<form action="{% url 'cart:cart_add' product.id %}" method="post">
						{{item.update_quantity_form.quantity}}
						{{item.update_quantity_form.override}}
						<input class="btn" type="submit" value="Update" />
						{% csrf_token %}
					</form>
				</td>
				<td>
					<form action="{% url 'cart:cart_remove' product.id %}" method="post">
						<input class="btn" type="submit" value="Remove" />
						{% csrf_token %}
					</form>
				</td>
				<td class="num">${{ item.price }}</td>
				<td class="num">${{ item.total_price }}</td>
			</tr>

			{% endwith %} {% endfor %}
			<tr style="height: 100px;"></tr>
			<tr class="cart-total">
				<td colspan="4"></td>
				<td><strong>Total</strong></td>
				<td class="num">${{ cart.total_price }}</td>
			</tr>
		</tbody>
	</table>
	<div class="checkout-btn-box">
		<div>
			<a href="{% url 'orders:order_create' %}"><button>Checkout</button></a>
		</div>
		<br />
		<div>
			<a href="{% url 'home' %}"><button>Continue shopping</button> </a>
		</div>
	</div>
	{% else %}
	{% endif %}
</div> 

{% endblock %}