mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('ecomapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('orders/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }

        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })

        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())
    
def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')


                                            

payment/templates/payment/canceled.html
{% extends "base.html" %} {% block content %}
<h1>Your payment has not been processed</h1>
<p>There was a problem processing your payment.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends "base.html" %} {% load static %} {% block content %}
<div class="payment-complete-box">
	<h1>Success!</h1>
	<img src="{% static 'img/checkmark.png' %}" style="height: 100px;" />
	<p>
		Your payment has been processed successfully. Thank you for your purchase!
	</p>
</div>
{% endblock %}

payment/templates/payment/process.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<div class="payment-box">
	<h1>Order summary</h1>
	<table class="payment-info">
		<thead>
			<tr>
				<th></th>
				<th>Product</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			{% for item in order.items.all %}
			<tr>
				<td>
					<img
						src="{% if item.product.image %}{{ item.product.image.url }}
{% else %}{% static 'img/no_image.png' %}{% endif %}" style="height: 100px;" />
				</td>
				<td>{{ item.product.name }}</td>
				<td class="num">${{ item.price }}</td>
				<td class="num">{{ item.quantity }}</td>
				<td class="num">${{ item.get_cost }}</td>
			</tr>
			{% endfor %}
			<tr style="height: 100px;"></tr>
			<tr class="total">
				<td colspan="3"></td>
				<td><strong>Total</strong></td>
				<td class="num">${{ order.total_cost }}</td>
			</tr>
		</tbody>
	</table>
	<form style="text-align: right;" action="{% url 'payment:process' %}" method="post">
		<input class="btn" type="submit" value="Pay now" />
		{% csrf_token %}
	</form>
	{% endblock %}
</div>